config/routes.rb
Rails.application.routes.draw do
  resources :resultts
  resources :planns
  devise_for :users
  resources :projects
  resources :robots
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plann.rb
class Plann < ApplicationRecord
  has_one :resultt
  validates :title , uniqueness:true, presence:true
  validates :robotidd ,presence:true
  validates :projectidd ,presence:true
  validates :location, presence:true
  validates :procedure, presence:true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :projectidd, presence:true,uniqueness:true
  validates :title, presence:true, uniqueness:true
  validates :description, presence:true
end

app/models/resultt.rb
class Resultt < ApplicationRecord
  belongs_to :plann
  validates :plann_id, uniqueness:true
  validates :observation, presence:true

end

app/models/robot.rb
class Robot < ApplicationRecord
  validates :robottidd, presence:true,uniqueness:true
  validates :title, presence:true, uniqueness:true
  validates :description, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/planns_helper.rb
module PlannsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/resultts_helper.rb
module ResulttsHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid bg-dark">

  <div class="jumbotron-background">
    <img src="https://placeimg.com/2000/1000/nature" class="blur ">
  </div>

  <div class="container text-white">

    <h1 class="display-4">WELCOME TO PROJECT MANAGEMENT SYSTEM</h1>

  </div>
  <!-- /.container -->


</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>Copyright @nio</small>
    <nav>
    <ul>
    <li><%= image_tag "csir.png",size:"50"%></li>
    <li><%= image_tag "nio.png",size:"50"%></li>

    </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"> PROJECT MANAGEMENT SYSTEM
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <li class="nav-item dropdown">
     <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       List
     </a>
     <div class="dropdown-menu" aria-labelledby="navbarDropdown">

       <%= link_to ' Plans', plans_path %>
       <div class="dropdown-divider"></div>
       <%= link_to ' Result', results_path %>
       <div class="dropdown-divider"></div>
     </div>
   </li>


      <li class="nav-item">
        <%if user_signed_in? %>
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             CREATE
           </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdown">
             <%= link_to 'New Plan', new_plan_path %>
             <div class="dropdown-divider"></div>
             <%= link_to 'New Result', new_result_path %>
             <div class="dropdown-divider"></div>
           </div>
         </li>
         <% end %>



               <li class="nav-item">
                 <%if user_signed_in? && current_user.admin?%>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      CREATE(Admin)
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <%= link_to 'New Project', new_project_path %>
                      <div class="dropdown-divider"></div>
                      <%= link_to 'New Robot', new_robot_path %>
                      <div class="dropdown-divider"></div>

                    </div>
                  </li>
                  <% end %>





      <li class="nav-item">
        <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
       <%= link_to 'Edit profile', edit_user_registration_path %> |
         <li><%= link_to "Sign out",destroy_user_session_path, method: :delete %></li>
           <a href="#"  aria-expanded="false">Profile<%= "(admin)" if current_user.admin? %><span class="caret"></span></a>
       <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
    <li><%= link_to 'Sign Up', new_user_registration_path %></li>
       <% end %>
     </ul>
      </li>
    </ul>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>NIO-ProApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <div >
      <%= render 'layouts/navigation' %>
      <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/footer' %>


    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

app/views/planns/_form.html.erb
<%= form_with(model: plann, local: true) do |form| %>
  <% if plann.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plann.errors.count, "error") %> prohibited this plann from being saved:</h2>

      <ul>
        <% plann.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :robotidd %>
 <%= form.collection_select(:robotidd, Robot.all, :robotidd,:title, { :prompt => 'Select a Robot', :selected => @robotidd}, { class: 'form-control' }) %>
  </div>

  <div class="field">
    <%= form.label :projectidd %>
    <%= form.collection_select(:projectidd, Project.all, :projectidd,:title, { :prompt => 'Select a Project', :selected => @projectidd}, { class: 'form-control' }) %>
  </div>

  <div class="field">
    <%= form.label :instruments %>
    <%= form.text_area :instruments %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="field">
    <%= form.label :procedure %>
    <%= form.text_area :procedure %>
  </div>

  <div class="field">
    <%= form.label :objective %>
    <%= form.text_area :objective %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/planns/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plann: @plann %>

<%= link_to 'Show', @plann %> |
<%= link_to 'Back', planns_path %>

app/views/planns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Robotidd</th>
      <th>Projectidd</th>
      <th>Instruments</th>
      <th>Location</th>
      <th>Procedure</th>
      <th>Objective</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planns.each do |plann| %>
      <tr>
        <td><%= plann.title %></td>
        <td><%= plann.robotidd %></td>
        <td><%= plann.projectidd %></td>
        <td><%= plann.instruments %></td>
        <td><%= plann.location %></td>
        <td><%= plann.procedure %></td>
        <td><%= plann.objective %></td>
        <td><%= plann.comments %></td>
        <td><%= link_to 'Show', plann %></td>
        <td><%= link_to 'Edit', edit_plann_path(plann) %></td>
        <td><%= link_to 'Destroy', plann, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plann_path %>

app/views/planns/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plann: @plann %>

<%= link_to 'Back', planns_path %>

app/views/planns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @plann.id %>
</p>


<p>
  <strong>Title:</strong>
  <%= @plann.title %>
</p>

<p>
  <strong>Robotidd:</strong>
  <%= @plann.robotidd %>
</p>

<p>
  <strong>Projectidd:</strong>
  <%= @plann.projectidd %>
</p>

<p>
  <strong>Instruments:</strong>
  <%= @plann.instruments %>
</p>

<p>
  <strong>Location:</strong>
  <%= @plann.location %>
</p>

<p>
  <strong>Procedure:</strong>
  <%= @plann.procedure %>
</p>

<p>
  <strong>Objective:</strong>
  <%= @plann.objective %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @plann.comments %>
</p>

<%= link_to 'Edit', edit_plann_path(@plann) %> |
<%= link_to 'Back', planns_path %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :projectidd %>
    <%= form.text_field :projectidd %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Projectidd</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.projectidd %></td>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Projectidd:</strong>
  <%= @project.projectidd %>
</p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>